version = 0.1

[default.deploy.parameters]
stack_name = "report-generator"
resolve_s3 = true
s3_prefix = "report-generator"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default.global.parameters]
region = "us-east-1"